# Generated by Django 5.2.1 on 2025-05-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("current_price", models.DecimalField(decimal_places=3, max_digits=20)),
                ("trading_money_volume", models.CharField(max_length=20)),
                ("trading_value", models.CharField(max_length=20)),
                ("market_cap", models.CharField(max_length=20)),
                ("week52_high", models.DecimalField(decimal_places=3, max_digits=20)),
                ("week52_low", models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
    ]
