# Generated by Django 5.2.1 on 2025-05-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="current_price",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="stock",
            name="market_cap",
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name="stock",
            name="week52_high",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="stock",
            name="week52_low",
            field=models.CharField(max_length=20),
        ),
    ]
