# Generated by Django 5.2.1 on 2025-06-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('item_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='주식 이름')),
                ('close_price', models.CharField(blank=True, max_length=20, null=True, verbose_name='현재가')),
                ('compare_to_previous_close_price', models.CharField(blank=True, max_length=20, null=True, verbose_name='전일비')),
                ('fluctuations_ratio', models.CharField(blank=True, max_length=20, null=True, verbose_name='등락률')),
                ('accumulated_trading_volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='거래량')),
                ('accumulated_trading_value_krw_hangeul', models.CharField(blank=True, max_length=50, null=True, verbose_name='거래대금(억)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '주식 정보',
                'verbose_name_plural': '주식 정보',
                'ordering': ['-accumulated_trading_volume'],
            },
        ),
    ]
