# Generated by Django 5.2.3 on 2025-06-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_stockmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_name", models.CharField(max_length=100)),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
